---
name: Static Code Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  static_code_analysis:
    uses: "mhashizume/phoenix-github-actions/.github/workflows/static_code_analysis.yaml@9978b4c4acab6c3e719ae48e8c37811ef8b2c8c1"
